version: "3.2"
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    domainname: rabbitmq.com
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./data:/data
  acl-queries:
    volumes:
      - ./acl/:/mnt/
    build: ./acl
    working_dir: /backend/
    command: sh run.sh
  jwt-queries:
    volumes:
      - ./jwt/:/mnt/
    build: ./jwt
    working_dir: /backend/
    command: sh run.sh
  sesiones-commands:
    volumes:
      - ./sesiones/:/mnt/
    build: ./sesiones
    working_dir: /backend/
    command: sh run_commands.sh
    environment:
      AMQP_URL: "amqp://rabbitmq?connection_attempts=10&retry_delay=10&heartbeat=600"
    depends_on:
      - rabbitmq
  notificaciones-commands:
    volumes:
      - ./notificaciones/:/mnt/
    build: ./notificaciones
    working_dir: /backend/
    command: sh run_commands.sh
    environment:
      AMQP_URL: "amqp://rabbitmq?connection_attempts=10&retry_delay=10"
    depends_on:
      - rabbitmq
  personas-commands:
    volumes:
      - ./personas/:/mnt/
    build: ./personas
    working_dir: /backend/
    command: sh run_commands.sh
  personas-queries:
    volumes:
      - ./personas/:/mnt/
    build: ./personas
    working_dir: /backend/
    command: sh run_queries.sh
  actividades-commands:
    volumes:
      - ./actividades/:/mnt/
    build: ./actividades
    working_dir: /backend/
    command: sh run_commands.sh
  actividades-queries:
    volumes:
      - ./actividades/:/mnt/
    build: ./actividades
    working_dir: /backend/
    command: sh run_queries.sh
  nginx:
    image: nginx:latest
    ports:
      - 5000:80
    volumes:
      - ./nginx/nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - sesiones-commands
      - notificaciones-commands
      - personas-commands
      - actividades-commands
      - personas-queries
      - actividades-queries
      - jwt-queries

networks:
  rabbitmq_go_net:
    driver: bridge
