version: "3.2"
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    domainname: rabbitmq.com
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./data:/data
  sesiones-commands:
    volumes:
      - ./sesiones/:/mnt/
    build: ./sesiones
    working_dir: /backend/
    command: sh run_commands.sh
    environment:
      AMQP_URL: "amqp://rabbitmq?connection_attempts=10&retry_delay=10"
    depends_on:
      - rabbitmq
  notificaciones-commands:
    volumes:
      - ./notificaciones/:/mnt/
    build: ./notificaciones
    working_dir: /backend/
    command: sh run_commands.sh
    environment:
      AMQP_URL: "amqp://rabbitmq?connection_attempts=10&retry_delay=10"
    depends_on:
      - rabbitmq
  nginx:
    image: nginx:latest
    ports:
      - 5000:80
    volumes:
      - ./nginx/nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - sesiones-commands
      - notificaciones-commands

networks:
  rabbitmq_go_net:
    driver: bridge
